"""Pinned OpenAPI slice for the endpoints other systems consume.

Citrus, Orange, and Palette read dish/fish identity from a handful of JSON
endpoints. This module extracts just those operations (plus every schema they
reference) from the app's generated OpenAPI document, so the committed copy
in ``docs/api/consumer_openapi.json`` can be diffed against the code.

Semantics (what ``revision`` means, stability promises) live in
``docs/zebrobot_snapshot.md``; this file only pins shapes.

Regenerate after an intentional change:

    pixi run python scripts/export_consumer_openapi.py
"""

import hashlib
import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple

from fastapi import FastAPI

CONSUMER_ENDPOINTS: List[Tuple[str, str]] = [
    ("get", "/dishes/{dish_id}/citrus-snapshot"),
    ("get", "/acquisition/dishes"),
    ("get", "/dishes/{dish_id}"),
    ("get", "/dishes/by-uuid/{dish_uuid}"),
    ("get", "/dishes/{dish_id}/fish"),
    ("get", "/fish/{fish_id}"),
    ("get", "/version"),
]

CONSUMER_OPENAPI_PATH = (
    Path(__file__).resolve().parents[2] / "docs" / "api" / "consumer_openapi.json"
)

_SCHEMA_REF_PREFIX = "#/components/schemas/"


def _refs(node: Any) -> Iterable[str]:
    """Yield every component schema name referenced anywhere under ``node``."""
    if isinstance(node, dict):
        ref = node.get("$ref")
        if isinstance(ref, str) and ref.startswith(_SCHEMA_REF_PREFIX):
            yield ref[len(_SCHEMA_REF_PREFIX):]
        for value in node.values():
            yield from _refs(value)
    elif isinstance(node, list):
        for value in node:
            yield from _refs(value)


def consumer_openapi(app: FastAPI) -> Dict[str, Any]:
    """Return the consumer-facing OpenAPI slice of ``app``."""
    full = app.openapi()
    paths: Dict[str, Any] = {}
    for method, path in CONSUMER_ENDPOINTS:
        operation = full["paths"][path][method]
        paths.setdefault(path, {})[method] = operation

    all_schemas = full.get("components", {}).get("schemas", {})
    needed: Dict[str, Any] = {}
    pending = list(_refs(paths))
    while pending:
        name = pending.pop()
        if name in needed:
            continue
        needed[name] = all_schemas[name]
        pending.extend(_refs(needed[name]))

    return {
        "openapi": full["openapi"],
        "info": {
            "title": "MetaZebrobot consumer API (pinned slice)",
            "description": (
                "Generated by scripts/export_consumer_openapi.py from the "
                "MetaZebrobot app; do not edit by hand. Semantics: "
                "docs/zebrobot_snapshot.md."
            ),
            "version": full["info"].get("version", ""),
        },
        "paths": paths,
        "components": {"schemas": needed},
    }


def render(schema: Dict[str, Any]) -> str:
    """Deterministic JSON text for committing and hashing."""
    return json.dumps(schema, indent=2, sort_keys=True) + "\n"


def digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()
